version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=netfood
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-provision:
    image: mongo:latest
    command: mongoimport -u root -p pass --host mongodb --db netfood --collection plats --type json --file /plats.json --jsonArray --authenticationDatabase admin
    volumes:
      - ./Netfood_BDD/plats.json:/plats.json
    depends_on:
      - mongodb
  back:
    build: ./NetFood_Back-End/
    ports:
      - 5000:5000
  front:
    build: ./NetFood_Front-End/
    ports:
      - 3000:3000
