version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=netfood
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-provision:
    # image: mongo:latest
    # volumes:
    #   - ./Netfood_BDD/plats.json:/plats.json

    image:  ksoul59/netfood_bdd:2
    command: mongoimport -u root -p pass --host mongodb --db netfood --collection plats --type json --file /plats.json --jsonArray --authenticationDatabase admin

    depends_on:
      - mongodb
  back:
    image: ksoul59/netfood_back:1.0
    ports:
      - 5000:5000
  front:
    image: ksoul59/netfood_front:1.0
    ports:
      - 3000:3000
